{#await promise catch error}
	<p>The error is {error}</p>
{/await}
